name: Build Android
description: Build and upload Android Binaries

inputs:
  GOOGLE_SERVICE_ACCOUNT_JSON:
    description: 'Android keystore in Base64'
    required: true
  PUBLISH_CHANNEL:
    description: 'Play Store publish channel (internal > alpha > beta > production)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create service_account.json
      run: echo '${{ inputs.GOOGLE_SERVICE_ACCOUNT_JSON }}' > google_service_account.json
      shell: bash

    - name: Deploy to Play Store - Internal
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: google_service_account.json
        packageName: com.eadev.accounting
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: ${{ inputs.PUBLISH_CHANNEL }}
        status: draft
        whatsNewDirectory: distribution/whatsnew/
